import type { Competition } from './types';

// 2026-2027 Canadian All-Star cheer season.
// Dates based on confirmed announcements + historical patterns.
// Marked with seeded: true so the app can distinguish them from user-created events.
export const SEEDED_COMPETITIONS: Competition[] = [
  // ── FALL 2026 ──────────────────────────────────────────────────
  {
    id: 'seed-cheer-for-cure-2026',
    name: 'Cheer for the Cure',
    venue: 'Paramount Fine Foods Centre',
    city: 'Mississauga, ON',
    startDate: '2026-11-27',
    endDate: '2026-11-29',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  // ── JANUARY 2027 ───────────────────────────────────────────────
  {
    id: 'seed-tidal-blast-2027',
    name: 'Tidal Blast',
    venue: 'Moncton Coliseum',
    city: 'Moncton, NB',
    startDate: '2027-01-22',
    endDate: '2027-01-23',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-big-east-blast-2027',
    name: 'Big East Blast',
    venue: 'EY Centre',
    city: 'Ottawa, ON',
    startDate: '2027-01-24',
    endDate: '2027-01-25',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-cheer-fest-2027',
    name: 'Canadian Cheer Fest',
    venue: 'Abbotsford Centre',
    city: 'Abbotsford, BC',
    startDate: '2027-01-31',
    endDate: '2027-02-01',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  // ── FEBRUARY 2027 ──────────────────────────────────────────────
  {
    id: 'seed-cheer-evo-ontario-2027',
    name: 'Cheer Evolution Ontario Championships',
    venue: 'The Aud',
    city: 'Kitchener, ON',
    startDate: '2027-02-12',
    endDate: '2027-02-14',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-spirit-sports-clash-2027',
    name: 'Spirit Sports Canadian Clash',
    venue: 'EY Centre',
    city: 'Ottawa, ON',
    startDate: '2027-02-20',
    endDate: '2027-02-21',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-battle-border-2027',
    name: 'Battle at the Border',
    venue: 'Scotiabank Convention Centre',
    city: 'Niagara Falls, ON',
    startDate: '2027-02-20',
    endDate: '2027-02-21',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-big-east-showdown-2027',
    name: 'Big East Showdown',
    venue: 'CAA Centre',
    city: 'Brampton, ON',
    startDate: '2027-02-27',
    endDate: '2027-02-28',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-quebec-champs-2027',
    name: 'Quebec Championships',
    venue: 'Centre des Congrès',
    city: 'Québec City, QC',
    startDate: '2027-02-20',
    endDate: '2027-02-21',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  // ── MARCH 2027 ─────────────────────────────────────────────────
  {
    id: 'seed-atlantic-showdown-2027',
    name: 'Atlantic Showdown',
    venue: 'Moncton Coliseum',
    city: 'Moncton, NB',
    startDate: '2027-02-28',
    endDate: '2027-03-01',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-ontario-provs-2027',
    name: 'Ontario Cheer Provincial Championship',
    venue: 'CAA Centre',
    city: 'Brampton, ON',
    startDate: '2027-03-05',
    endDate: '2027-03-07',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  // ── APRIL 2027 (Nationals Weekend — Mississauga) ───────────────
  {
    id: 'seed-worlds-faceoff-2027',
    name: 'Canadian Worlds Face-Off',
    venue: 'Paramount Fine Foods Centre',
    city: 'Mississauga, ON',
    startDate: '2027-04-09',
    endDate: '2027-04-09',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-canadian-finals-2027',
    name: 'Canadian Cheer Finals',
    venue: 'Paramount Fine Foods Centre',
    city: 'Mississauga, ON',
    startDate: '2027-04-10',
    endDate: '2027-04-10',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  {
    id: 'seed-allstar-nationals-2027',
    name: 'Canadian All-Star Nationals',
    venue: 'Paramount Fine Foods Centre',
    city: 'Mississauga, ON',
    startDate: '2027-04-09',
    endDate: '2027-04-12',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
  // ── MAY 2027 ───────────────────────────────────────────────────
  {
    id: 'seed-school-nationals-2027',
    name: 'Canadian School Nationals',
    venue: 'EY Centre',
    city: 'Ottawa, ON',
    startDate: '2027-05-08',
    endDate: '2027-05-09',
    divisions: [],
    status: 'upcoming',
    createdAt: 0,
  },
];

export const SEED_VERSION_KEY = 'cheerhub:seeded:v1';
